---
abstract: 'Web interface to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  Dancer::Test: 0
  File::Find: 0
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Server
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Server:
    file: lib/Pinto/Server.pm
    version: 0.020
  Pinto::Server::Routes:
    file: lib/Pinto/Server/Routes.pm
    version: 0.020
requires:
  Carp: 0
  Dancer: 0
  File::Temp: 0
  Getopt::Long: 0
  Moose: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Pinto: 0.023
  Pinto::Types: 0
  Pod::Usage: 0
  perl: 5.006
resources:
  homepage: https://github.com/thaljef/Pinto-Server
  repository: https://github.com/thaljef/Pinto-Server
version: 0.020
