---
abstract: 'Web interface to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  Apache::Htpasswd: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  FindBin: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  List::Util: 0
  Module::Build: 0.3601
  PerlIO::gzip: 0
  Pinto::Tester::Util: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Server
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Server:
    file: lib/Pinto/Server.pm
    version: 0.047
  Pinto::Server::Responder:
    file: lib/Pinto/Server/Responder.pm
    version: 0.047
  Pinto::Server::Responder::Action:
    file: lib/Pinto/Server/Responder/Action.pm
    version: 0.047
  Pinto::Server::Responder::File:
    file: lib/Pinto/Server/Responder/File.pm
    version: 0.047
  Pinto::Server::Responder::Index:
    file: lib/Pinto/Server/Responder/Index.pm
    version: 0.047
  Pinto::Server::Router:
    file: lib/Pinto/Server/Router.pm
    version: 0.047
  Pinto::Server::Tester:
    file: lib/Pinto/Server/Tester.pm
    version: 0.047
requires:
  Authen::Simple::Passwd: 0
  Carp: 0
  Class::Load: 0
  File::Copy: 0
  File::Temp: 0
  File::Which: 0
  Getopt::Long: 0
  IO::Handle::Util: 0
  IO::Interactive: 0
  IO::Pipe: 0
  IPC::Run: 0
  JSON: 0
  List::MoreUtils: 0
  Log::Dispatch::Handle: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  MooseX::Types::Moose: 0
  POSIX: 0
  Path::Class: 0
  Pinto: 0.046
  Pinto::Constants: 0
  Pinto::Result: 0
  Pinto::Tester: 0
  Pinto::Types: 0
  Plack::MIME: 0
  Plack::Middleware::Auth::Basic: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Runner: 0
  Pod::Usage: 0
  Proc::Fork: 0
  Router::Simple: 0
  Scalar::Util: 0
  Test::TCP: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Server/issues
  repository: git://github.com/thaljef/Pinto-Server.git
version: 0.047
