---
abstract: 'Web interface to a Pinto repository'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  Apache::Htpasswd: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Module::Build: 0.3601
  Pinto::Tester: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto-Server
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto::Server:
    file: lib/Pinto/Server.pm
    version: 0.037
  Pinto::Server::ActionResponder:
    file: lib/Pinto/Server/ActionResponder.pm
    version: 0.037
  Pinto::Server::ActionResponder::Splatting:
    file: lib/Pinto/Server/ActionResponder/Splatting.pm
    version: 0.037
  Pinto::Server::ActionResponder::Streaming:
    file: lib/Pinto/Server/ActionResponder/Streaming.pm
    version: 0.037
  Pinto::Server::Handler:
    file: lib/Pinto/Server/Handler.pm
    version: 0.037
requires:
  Authen::Simple::Passwd: 0
  Carp: 0
  Class::Load: 0
  File::Copy: 0
  Getopt::Long: 0
  IO::Handle::Util: 0
  IO::Interactive: 0
  IO::Pipe: 0
  IO::String: 0
  List::MoreUtils: 0
  List::Util: 0
  Log::Dispatch::Handle: 0
  Moose: 0
  MooseX::ClassAttribute: 0
  MooseX::NonMoose: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Pinto: 0.036
  Pinto::Constants: 0
  Pinto::Result: 0
  Pinto::Types: 0
  Plack::Component: 0
  Plack::MIME: 0
  Plack::Middleware::Auth::Basic: 0
  Plack::Request: 0
  Plack::Response: 0
  Plack::Runner: 0
  Pod::Usage: 0
  Proc::Fork: 0
  Scalar::Util: 0
  Try::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto-Server/issues
  repository: git://github.com/thaljef/Pinto-Server.git
version: 0.037
